# Generated by Django 2.0.13 on 2019-07-15 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('username', models.CharField(max_length=30)),
                ('hostname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('device_type', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_int', models.CharField(max_length=20)),
                ('mac', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('Access', 'access'), ('Trunk', 'trunk')], max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layer2.Device')),
            ],
        ),
    ]
