# Generated by Django 2.0.13 on 2019-07-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layer2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='ip',
            new_name='ip_vlan',
        ),
    ]
