# Generated by Django 2.0.13 on 2019-07-16 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layer2', '0002_auto_20190715_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='status',
            field=models.BooleanField(choices=[('up', 'UP'), ('down', 'DOWN')], default=False),
        ),
    ]
